<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <head>
    <title>Daily Promise<?php echo($titleText); ?></title>
	<link rel="shortcut icon" href="/favicon.ico">
	<link type="text/css" rel="stylesheet" media="all" href="/default.css" />
	<script src="http://platform.twitter.com/anywhere.js?id=aTluCSNqhyz2mRNVLth1ZQ&v=1" type="text/javascript"></script>
  </head>
  <body>
	
    <div id="header">
        <a href="/" id="sitename"><img src="/images/logo.png" alt="Daily Promise" title="Daily Promise"/></a>
        <?php echo($headerContent); ?>
    </div>
    
	<div id="<?php echo($contentPage); ?>content"><?php echo($content); ?></div>
	
    <div id="footer">Daily Promise is a website by Ian Renton.</div>

</body></html>
