<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <head>
    <title>Daily Promise</title>
	<link rel="shortcut icon" href="favicon.ico">
	<link type="text/css" rel="stylesheet" media="all" href="/default.css" />
	<!--[if lt IE 7]>
      	<link type="text/css" rel="stylesheet" media="all" href="/ie.css" />
    <![endif]-->

  </head>
  <body>
	<SCRIPT LANGUAGE="JavaScript" SRC="javascript.js"></SCRIPT>
	
    <div id="header">
        <a href="/" id="sitename">Daily Promise</a>
        <?php echo($headerContent); ?>
    </div>
    
	<div id="content"><?php echo($content); ?></div>
	
    <div id="footer">Daily Promise is a website by Ian Renton.</div>
	
    <SCRIPT LANGUAGE="JavaScript">
        window.onload=init();
    </SCRIPT>

</body></html>
